name: Security Pipeline

on:
  push:
    # Проверяем пуши во все ветки
    branches: [ "**" ]
  pull_request:
    # Проверять пулл реквест перед слиянием
    types: [opened, synchronize, reopened]
    # Выбор путей
    #path:
    #  - '...'
    #  - '...'

jobs:
  Secrets:
    name: Secret Detection — ${{ matrix.scanner }}  # <--- Динамическое имя!
    runs-on: ubuntu-latest
    strategy:
      # Запрет быстрого завершение оставшихся задач, если упадет предыдущая
      fail-fast: false
      # Размножение задач на независимые параллельные задачи
      matrix:
        # Запуск параллельных задач
        scanner: [trufflehog, gitleaks]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Скачиваем историю, чтобы Git мог сравнить коммиты

      - name: TruffleHog
        if: matrix.scanner == 'trufflehog'
        uses: trufflesecurity/trufflehog@main
        with:
          # event.before содержит хэш до пуша. Мы проверяем изменения от него до текущего HEAD.
          base: ${{ github.event.before }}
          head: HEAD
          extra_args: --results=verified,unknown

      - name: Gitleaks
        if: matrix.scanner == 'gitleaks'
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: ${{ github.workspace }}/.gitleaks.toml

  SCA:
    name: Software Component Analysis — ${{ matrix.sca }}  # <--- Динамическое имя!
    runs-on: ubuntu-latest
    strategy:
      # Запрет быстрого завершение оставшихся задач, если упадет предыдущая
      fail-fast: false
      # Размножение задач на независимые параллельные задачи
      matrix:
        # Запуск параллельных задач
        sca: [owasp, trivy]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check
        # if: matrix.sca == 'owasp'
        # Модуль отключен - false, true - включен
        if: false
        uses: dependency-check/Dependency-Check_Action@main
        id: DependencyCheck
        with:
          project: 'AI-SEC-PLATFORM'
          path: '.'
          # Выходной формат файла
          format: 'SARIF,HTML'
          # --enableRetired - поиск устаревших библиотек JS
          # --failOnCVSS 3 - пайплайн упадет если CVSS >= 3.0
          # --enableHighRiskIndex - высокорискованные методы анализа
          # NVD_API_KEY - ключ качает инфу об уязвимостях
          args: >
            --failOnCVSS 3
            --nvdApiKey ${{ secrets.NVD_API_KEY }}

      - name: Trivy SCA
        if: matrix.sca == 'trivy'
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "fs"
          scan-ref: "."
          scanners: "vuln"
          format: "json"
          output: "trivy.json"
          exit-code: "0"
          severity: "CRITICAL,HIGH,MEDIUM,LOW"

      - name: Upload Trivy result
        # Добавить условие, иначе шаг выполнился бы для обоих задач и для owasp и для trivy 
        if: matrix.sca == 'trivy'
        uses: actions/upload-artifact@v4
        with:
          name: trivy-result
          path: trivy.json

  SAST:
    name: SAST — ${{ matrix.sast }}  # <--- Динамическое имя!
    runs-on: ubuntu-latest
    strategy:
      # Запрет быстрого завершение оставшихся задач, если упадет предыдущая
      fail-fast: false
      # Размножение задач на независимые параллельные задачи
      matrix:
        # Запуск параллельных задач
        sast: [semgrep-auto, semgrep-my-rules]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.after }}
          # Скачиваем всю историю коммитов, без самих файлов старых коммитов. Git видит всю цепочку изменений!
          filter: tree:0
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Semgrep
        run: pip install semgrep

      - name: Cache Semgrep rules
        if: matrix.sast == 'semgrep-auto'
        id: semgrep-cache
        uses: actions/cache@v4
        with:
          path: .semgrep-rules
          key: semgrep-rules-v1

      - name: Download Semgrep rules
        if: matrix.sast == 'semgrep-auto' && steps.semgrep-cache.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 https://github.com/semgrep/semgrep-rules.git .semgrep-rules
          rm -rf .semgrep-rules/stats
          rm .semgrep-rules/LICENSE
          rm .semgrep-rules/Pip*
          rm .semgrep-rules/Makefile
          rm .semgrep-rules/CO*
          rm .semgrep-rules/metadata*
          rm .semgrep-rules/README.md
          rm .semgrep-rules/template*
          rm .semgrep-rules/SECURITY.md
          rm .semgrep-rules/.pre-commit-config.yaml
          rm -rf .semgrep-rules/.git*

        # Список измененных файлов - разделены пробелом для Semgrep
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          base_sha: ${{ github.event.before }}
          sha: ${{ github.event.after }}
          diff_relative: true
          files_separator: " " # Semgrep принимает файлы через пробел

        # Запуск Semgrep только если есть измененные файлы
      - name: Run Semgrep
        if: matrix.sast == 'semgrep-auto' && steps.changed-files.outputs.any_changed == 'true'
        run: semgrep scan --config .semgrep-rules --json --output semgrep-auto.json ${{ steps.changed-files.outputs.all_changed_files }}

      #- name: Run Semgrep
      #  run: semgrep scan --config .semgrep-rules . --json --output semgrep.json

      - name: Upload Semgrep result
        if: matrix.sast == 'semgrep-auto'
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-auto-rules-result
          path: semgrep-auto.json

        # Запуск Semgrep со своими правилами
      - name: Check My Semgrep Rules Exist
        if: matrix.sast == 'semgrep-my-rules'
        id: check-my-rules
        run: |
          if [ ! -d "security/SAST/semgrep" ]; then
            echo "::notice::Semgrep rules directory not found: security/SAST/semgrep Skipping scan for semgrep-my-rules."
            echo "rules_missing=true" >> $GITHUB_OUTPUT
            #exit 1
          else
            echo "rules_missing=false" >> $GITHUB_OUTPUT
          fi

      - name: Run Semgrep My Rules
        if: matrix.sast == 'semgrep-my-rules' && steps.check-my-rules.outputs.rules_missing == 'false' && steps.changed-files.outputs.any_changed == 'true'
        run: semgrep scan --config security/SAST/semgrep --json --output semgrep-my-rules.json ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Create Empty Result If Rules Missing
        if: matrix.sast == 'semgrep-my-rules' && steps.check-rules.outputs.rules_missing == 'true'
        run: echo "{\"results\":[],\"errors\":[\"Semgrep rules not found\"]}" > semgrep-my-rules.json

      - name: Upload Semgrep My Rules Result
        if: matrix.sast == 'semgrep-my-rules'
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-my-rules-result
          path: semgrep-my-rules.json





  SAST_GATE:
    #needs: [Secrets, SCA]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      #- name: Download Trivy result
      #  uses: actions/download-artifact@v5
      #  with:
      #    name: trivy-result

      #- name: Security gate
      #  run: python security/security_gate.py

  DAST:
    needs: [SAST_GATE]
    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        dast_scanner: [nuclei, nuclei-custom, zap-baseline, zap-full]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # Новый подход к сборке Docker (Buildx)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Сборка с сохранением и чтением кэша из GitHub
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ai-sec-platform:${{ github.sha }}
          outputs: type=docker,dest=/tmp/image.tar    # Сохранение образа в артефакты для запуска на этой же машине
          cache-from: type=gha                        # Поиск кэша прошлых сборок в облаке GitHub
          cache-to: type=gha,mode=max                 # Запись нового кэша библиотек в облако GitHub

      # Загрузка образа в артефакты
      - name: Upload Docker Image to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-ai-sec-platform-${{ github.run_number }}
          path: /tmp/image.tar
          retention-days: 5                        # Дни хранения

      # Загрузка образа в локальный Docker движок Runner
      - name: Load Docker image
        run: docker load -i /tmp/image.tar

      # Trivy проверка образа
      - name: Trivy image scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ai-sec-platform:${{ github.sha }}
          format: json
          output: trivy-docker-image.json
          severity: CRITICAL,HIGH,MEDIUM
          exit-code: 0

      # Сохранение отчета Trivy
      - name: Upload Trivy image scan result
        uses: actions/upload-artifact@v4
        with:
          name: trivy-docker-image-report    # Имя архива в GitHub
          path: trivy-docker-image.json      # Имя файла

      # Запуск контейнера
      - name: Run container
        run: docker run -d --name ai-sec-platform -p 8000:8000 ai-sec-platform:${{ github.sha }}

      - name: Check application
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:8000; then
              echo "Application is running"
              exit 0
            fi

            echo "Waiting for application..."
            sleep 2
          done

          echo "Application did not start"
          docker logs ai-sec-platform
          exit 1

      #- name: Setup Go
      #  uses: actions/setup-go@v6
      #  with:
      #    go-version: "1.26"

      #- name: Install Nuclei
      #  run: |
      #    go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
      #    echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      #- name: Update Nuclei templates
      #  run: |
      #    nuclei -version
      #    nuclei -update-templates

      - name: Restore ZAP image cache
        id: zap-cache
        uses: actions/cache/restore@v4
        with:
          path: /tmp/zap-image.tar
          key: zap-image-v1

      - name: Load ZAP image from cache
        if: steps.zap-cache.outputs.cache-hit == 'true'
        run: |
          docker load -i /tmp/zap-image.tar

      - name: Download ZAP image
        if: steps.zap-cache.outputs.cache-hit != 'true'
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Save ZAP image to cache
        if: steps.zap-cache.outputs.cache-hit != 'true'
        run: |
          docker save ghcr.io/zaproxy/zaproxy:stable -o /tmp/zap-image.tar

      - name: Save ZAP cache
        if: steps.zap-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: /tmp/zap-image.tar
          key: zap-image-v1

      - name: Run DAST scanners
        run: |
      #       nuclei -u http://localhost:8000 -jsonl -o nuclei.json &
      #       nuclei -u http://localhost:8000 -t ./security/DAST/nuclei/ -jsonl -o nuclei-custom.json -no-meta -omit-raw &
      #       # nuclei -u http://localhost:8000 -t security/DAST/nuclei/ -jsonl -o nuclei-custom.json &
      #       # zap-baseline.py -t http://localhost:8000 -J zap-baseline.json &
      #       # zap-full-scan.py -t http://localhost:8000 -J zap-full.json &
             docker run --rm --network host -v "$PWD:/zap/wrk" ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost:8000 -J zap-baseline.json &
             docker run --rm --network host -v "$PWD:/zap/wrk" ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t http://localhost:8000 -J zap-full.json &
             wait

      - name: Upload Nuclei Custom result
        uses: actions/upload-artifact@v4
        with:
          name: dast-results
          path: |
            #nuclei.json
            #nuclei-custom.json
            zap-baseline.json
            zap-full.json

  DAST_GATE:
    needs: [DAST]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download Nuclei Results
        uses: actions/download-artifact@v4
        with:
          name: dast-results
          # Файл скачается прямо в текущую рабочую директорию

      #- name: Gate parser
      #  run: python ./security/DAST/dast_gate.py nuclei.json nuclei-custom.json

      #- name: Upload DAST gate result
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: security-summary
      #    path: security-summary.json
